### ISSUE TITLE
Additional text is being trimmed or omitted

### ISSUE THREAD

**Issue by docmars** [preciousforever/sketch-data-populator#101]
Hey there,

**Version:** 2.1.3

I'm getting an issue where strings like `{symbol}:{exchange}` are resulting in just the `symbol` value, but the colon ( : ) and `exchange` are being left off.

Even in the demo file where you have `{company?Freelance} · {job?–}`, the only string coming in from the contacts demo JSON is the `company`.

**Comment by lukasondrej** [comment]
Hey @docmars, 

could you verify the name of the text layer. I believe the issue is that your layer name contains `{company?Freelance}` and hence only the company is populated. 

If the layer name contains placeholders, only the first one is considered and takes precedence over any placeholders in the text content of the layer.

You may wish to rename the text layer to not contain placeholders. 

Hope that helps.

**Comment by docmars** [comment]
Ahh got it. Thanks for the tip, I'll give it a try.

Awesome plugin, btw—I really wish this existed for Adobe Illustrator!
