### ISSUE TITLE
"Populate again" improvement

### ISSUE THREAD

**Issue by clarklab** [preciousforever/sketch-data-populator#11]
When I click "Populate again", nothing happens, because my {tags} are all gone, and the plugin sees nothing to populate. I'd LOVE IT if the plugin could actually repopulate all the zones again, sorta like a shuffle.

It seems like a great way to test to strength of my layout, to just shuffle one random set after another into place. Currently it seems like I'd need to maintain a "source" set of artboards, where I keep the {title} and such in place, and duplicate each time I wanted to populate.

Any way for the plugin to repopulate the same fields it's already touched? Perhaps instead of looking for {title} in the text field content itself, we could name the actual layer {title}, so the plugin would know to continually target it? Even after it's been populated once?

**Comment by nitrada** [comment]
you can re-populate images because they remain their {placeholder} layer name.

naming the text layer itself {placeholder} doesn't work since you can use several placeholders in one text layer (for concatenation, e.g. "{first_name} {last_name}" or "{quantity} x {price} = {subtotal}"). layout and truncation would be awkward with several text layers. 

but as commented in #10, we're already working on a solution to be able to re-populate text layers.
