### ISSUE TITLE
Parsing Arrays containing Objects

### ISSUE THREAD

**Issue by sdnyco** [preciousforever/sketch-data-populator#34]
Am I doing something wrong or is it currently not possible to parse arrays containing objects?

**See example below:**

``` JSON
[
  {
    "array": [
      {
        "id": 1,
        "details": "first details"
      },
      {
        "id": 2,
        "details": "more details"
      }
    ],
    "secondArray": [
      {
        "id": 3,
        "details": "just another object"
      }
    ]
  }
]
```

**Comment by nitrada** [comment]
this should be possible since https://github.com/preciousforever/sketch-data-populator/releases/tag/v1.2.1— shouldn't it, @lukas77me?

**Comment by nitrada** [comment]
@sdnyco I was wrong actually – at the time I replied it was possible to use nested data via dot path, but it's only since [v1.3.0](https://github.com/preciousforever/sketch-data-populator/releases/tag/v1.3.0) that nested arrays do work. can you give it a go with the recent version of the plugin and let us know if it worked?
