### ISSUE TITLE
creating grid with complex/nested JSON

### ISSUE THREAD

**Issue by leffi7** [preciousforever/sketch-data-populator#41]
Hi,

I need some help :)
Is there a way to add a 'need help' label to my issue? Couldn't find it...

I used a pretty complex JSON to populate a text in sketch. I successfully retrieved the title by naming the text layer: {sectionPage.primaryTeaserList[1].articleList[0].title}

Now I want to create a grid with the JSON populator. The grid should contain all titles from the 'articleList object'. So I need:
{sectionPage.primaryTeaserList[1].articleList[0].title}
{sectionPage.primaryTeaserList[1].articleList[1].title}
{sectionPage.primaryTeaserList[1].articleList[2].title}
...
{sectionPage.primaryTeaserList[1].articleList[6].title}

Any idea how to realize this in 1 'populate JSON command'? 

thx!

**Comment by nitrada** [comment]
hey @leffi7, that's not possible with Sketch Data Poplator's internal grid tool at the moment, since placeholders containing arrays need to be manually set up. what you could do is create the grid with Sketch's grid tool, then rename the text layers manually, then populate.

that's actually something we're currently thinking about: make it Data Populator more data-driven. 

right now, the paradigm is: create the layers to be populated first, then populate them with data. so if you use the internal grid tool, you probably noticed it always first creates the grid with the elements, then populates afterwards. there's no real connection between the elements and the data – Data Populator just runs over all selected elements and populates them if they contain placeholders. you could create a grid with 3 columns and 4 rows, and if your data contains 20 data sets, 8 of them will remain unpopulated.

the limitation is there's only one level of grids, and that grid is arbitrary. in your example data, there could be several levels of grids. we're exploring ways to incorporate this, where you rather add grid properties as meta data (tags) to the layers or layer groups to be populated. like this, you could have grids within grids, and we would always populate what's in the data (unless you probably limit a grid with a MAX property)… 

does this help for now? if you have ideas or specific requirements, let us know!

**Comment by leffi7** [comment]
Thank you Christophe!

Cool you guys continue to improve your product and keep thinking about solutions.

A data-populator in Sketch has so much potential and is in my opinion one of the most important plugins to work with.

Keep up the good work. Looking forward to see more improvements and features in the future...

Lef

Verstuurd vanaf mijn iPhone
