### ISSUE TITLE
Trimming text not working

### ISSUE THREAD

**Issue by rorysmyth** [preciousforever/sketch-data-populator#66]
This is a great feature that stopped working. Are there any plans to fix this? Using sketch 39.1

**Comment by nitrada** [comment]
@rorysmyth in order to make iconfonts work with data populator, we needed to make a few minor changes. just get rid of the curly brackets in the layer name and it should work. 

we're close to release a completely refactored version of the plugin and there will be more documentation coming with that. for a sneak peak, you can check the "refactoring" branch...

**Comment by rorysmyth** [comment]
Thanks @nitrada. Works like a charm!

Will check out the new branch. Great work btw

**Comment by nitrada** [comment]
@rorysmyth you'll like l | -l n" if you're into truncating text ;-)
