### ISSUE TITLE
Duplicating objects and clearing layer reverts to initial text

### ISSUE THREAD

**Issue by seanmpm** [preciousforever/sketch-data-populator#71]
Any duplicated text box reverts back to it's original state when I clear layers. 

So, option+drag, and then change the text to a new ID from the JSON, then import, then clear - it reverts to the oldest ID. It didn't used to work like this and it's ruined a lot of work because I copy design elements all over the place. Creating a new text box each time is inefficient.

**Comment by nitrada** [comment]
our desired behavior is: 'clear' reverts a selected text layer to its initial {placeholder}. this means there can only be ONE placeholder per layer. 

we did this because sometimes, we were quite irritated ourselves when we used an already populated layer, overwrote its data with another placeholder – but populating would always use the original placeholder, because it is stored in the layer as meta data. that's quite unpredictable.

also, we wanted a 'clear' that's really solid and works across different versions of the plugin (meta data on layers get usually linked to a specific plugin identifier). this is something we changed/added at some point. 

for us, this behavior works much better and is above all predictable. no surprises. 

if this makes your work more inefficient, could you please elaborate a bit more on what your desired 'clear' behavior would be?
