### ISSUE TITLE
Concatenation issues

### ISSUE THREAD

**Issue by ericazf** [preciousforever/sketch-data-populator#86]
Hi, I'm having trouble concatenating a string.

My JSON is like this:
`{
        "id": "1",
        "shop": "JuGás Liberdade",
        "streetname": "Av. Galvão Bueno",
        "number": "337",
        "neighbourhood": "Liberdade",
        "city": "São Paulo"
    }`

And on the Sketch file, I'm doing:
> {streetname}, {number} – {neighbourhood}, {city}

But for some reason when I run the script it just shows the street name.

It's also worth mentioning that I'm using this inside a symbol, but I tried out of the symbol and the same thing happens.

Is there something I'm doing wrong?
Thanks!

**Comment by nitrada** [comment]
@ericazf make sure the Layer name (in the Layers list on the left) is not called {streetname}. otherwise, the {placeholder} used in the Layer name will always overwrite all other {placeholders} inside a Text Layer's content (that's necessary if you use Iconfonts).

**Comment by ericazf** [comment]
Hi, thanks for your reply. Still not working, though.

I recorded my screen so you can check it out.
https://youtu.be/-o6SErFzPQ4

Weirdly, I realised that once I run the plugin, it hides the layer where the concatenation should happen. And when I show it again, the text inside is just a hyphen.

**Comment by nitrada** [comment]
hidden + hypen means there's no corresponding data in the JSON. since the JSON shown above has these data, it could also be that the layer was populated with other data before.

can you select the layer that is not working an clear it? if it shows {something} after clearing, replace this with your desired concatenation and it should work.

(the main issue here is that you cannot see on the UI if a layer already has data. we already have some ideas here.)

**Comment by ericazf** [comment]
It worked! Thanks a lot! :)

**Comment by nitrada** [comment]
you're welcome!
