### ISSUE TITLE
Problem loading non HTTPS images from URLs

### ISSUE THREAD

**Issue by Stompfrog** [preciousforever/sketch-data-populator#89]
I can get images to load fine in my prototype but only if they are served using HTTPS rather than HTTP. Some of the images I need to pull in are only available on an HTTP server and these fail with the following error...

'Some images could not be loaded. Please check the URLs.'

Any ideas?

Example JSON:
`{
	"secureImage" : "https://www.google.co.uk/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png",
	"insecureImage" : "http://www.google.co.uk/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
}`

**Comment by lukasondrej** [comment]
@Stompfrog as far as I know, it's not possible to load images over HTTP due to the App Transport Security restrictions which are enabled in Sketch. This means that Sketch only allows connections that are secure, e.g. over HTTPS. Unfortunately, it's not possible for us to overcome this issue at this point in time.
